controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

validate_route:
    path: /validate
    controller: App\Controller\MessageController::Response